//
//  MemoryStorage.swift
//  WanWo
//
//  【语义移植 · codex · M7 件 G · F043】出处（repos/codex-rust-v0.153.0-alpha.6）：
//    - memories/write/src/storage.rs 全文 —— rebuild_raw_memories_file（:44-78 逐语义：
//      "# Raw Memories\n\n" 头 / 空表 "No raw memories yet.\n" / "Merged stage-1 raw
//      memories (stable ascending thread-id order):\n\n" / 每条 "## Thread `<id>`" +
//      updated_at/cwd/rollout_path/rollout_summary_file 元数据行 + raw_memory.trim()
//      + "\n\n"）；sync_rollout_summaries_from_memories（keep 集合 prune + 逐线程写
//      rollout_summaries/<stem>.md，正文 = thread_id/updated_at/rollout_path/cwd/
//      [git_branch] 元数据 + rollout_summary）；rollout_summary_file_stem_from_parts
//      （:161-238 逐字：UTC %Y-%m-%dT%H-%M-%S 时间戳段 + uuid 低 32 位 % 14_776_336
//      → 4 字符 base62 hash；slug ≤60 ASCII 字母数字小写化、其余 '_'、尾 '_' 弹出）。
//    - memories/write/src/lib.rs —— ensure_layout（root 建目录 + symlink 拒绝 +
//      rollout_summaries 建目录）、artifacts 三常量。
//    - memories/write/src/workspace.rs —— validate_consolidation_artifacts
//      （:51-82 逐语义：MEMORY.md 存在且为文件；memory_summary.md 首行 == "v1"）；
//      remove_memory_symlinks（递归清除）；render_workspace_diff_file（:132-151
//      逐字文案："# Memory Workspace Diff\n\n Generated by Codex before Phase 2
//      …" + Status 行 "- <label> <path>" / "- none" + "## Diff\n\n```diff …```"；
//      MAX_BYTES 4MiB 截断）。
//    - 【已定适配③】git baseline → 自维护文件 hash 快照清单：diff = 上次成功
//      Phase2 的 MemorySnapshotManifest 与当前文件树逐路径比对（added=A/modified=M/
//      deleted=D，lexicographic path 序——git status 同序）；基线重置 = 重拍清单。
//      unified diff 体不再产出（manifest 无逐行 diff 面）——"## Diff" 节恒空标记
//      ```` ```diff ```` 空块，整合语义「以 Status 为权威变更队列」不变，登记。
//    - 万我元数据行：cwd/rollout_path 列万我会话事实源（header cwd /
//      sessions/<id>.jsonl 相对路径）；git_branch 万我无（条件行缺席语义一致）。
//

import Foundation

/// memory 工件（memory root 目录树：MEMORY.md / memory_summary.md /
/// raw_memories.md / rollout_summaries/ / extensions/ad_hoc/notes/）。
struct MemoryStorage {
    /// 宿主侧 memory 根（WanWoPaths.memoryPersistentDir——iSH bind mount
    /// 同一目录，guest 面 = /var/wanwo/memory）。
    let rootURL: URL
    /// 快照清单持久位（memory 根外：config/memory-snapshot.json——适配③）。
    let manifestURL: URL

    private static let fm = FileManager.default

    init(rootURL: URL, manifestURL: URL) {
        self.rootURL = rootURL
        self.manifestURL = manifestURL
    }

    // MARK: - 布局（ensure_layout）

    /// ensure_layout 1:1：root 建目录、root 非符号链接、递归清 symlink、
    /// rollout_summaries 建目录。
    func ensureLayout() throws {
        try Self.fm.createDirectory(at: rootURL, withIntermediateDirectories: true)
        guard (try? Self.fm.attributesOfItem(atPath: rootURL.path)) != nil else {
            throw MemoryError(message: "memory root unreadable: \(rootURL.path)")
        }
        _ = try removeMemorySymlinks()
        try Self.fm.createDirectory(
            at: rootURL.appendingPathComponent(MemoryConstants.rolloutSummariesSubdir),
            withIntermediateDirectories: true)
    }

    // MARK: - raw_memories.md（storage.rs :44-78）

    /// rebuild_raw_memories_file 逐语义（records 须 thread_id ASC——调用方保证，
    /// MemoryDatabase 读面已按序返回）。
    func rebuildRawMemoriesFile(_ records: [MemoryStage1Record],
                                maxRawMemoriesForConsolidation: Int,
                                cwdFor: (MemoryStage1Record) -> String) throws {
        try ensureLayout()
        let retained = Array(records.prefix(maxRawMemoriesForConsolidation))
        var body = "# Raw Memories\n\n"
        if retained.isEmpty {
            body += "No raw memories yet.\n"
            try write(body, to: rawMemoriesURL)
            return
        }
        body += "Merged stage-1 raw memories (stable ascending thread-id order):\n\n"
        for memory in retained {
            body += "## Thread `\(memory.threadId)`\n"
            body += "updated_at: \(Self.rfc3339(memory.sourceUpdatedAt))\n"
            body += "cwd: \(cwdFor(memory))\n"
            body += "rollout_path: \(Self.rolloutPathLabel(memory.threadId))\n"
            let stem = Self.rolloutSummaryFileStem(threadId: memory.threadId,
                                                   sourceUpdatedAt: memory.sourceUpdatedAt,
                                                   rolloutSlug: memory.rolloutSlug)
            body += "rollout_summary_file: \(stem).md\n"
            body += "\n"
            body += memory.rawMemory.trimmingCharacters(in: .whitespacesAndNewlines)
            body += "\n\n"
        }
        try write(body, to: rawMemoriesURL)
    }

    private var rawMemoriesURL: URL {
        rootURL.appendingPathComponent(MemoryConstants.rawMemoriesFilename)
    }

    // MARK: - rollout_summaries 同步（sync_rollout_summaries_from_memories）

    /// keep 集合 prune + 逐线程写摘要文件（storage.rs :23-42 逐语义）。
    func syncRolloutSummaries(_ records: [MemoryStage1Record],
                              maxRawMemoriesForConsolidation: Int,
                              cwdFor: (MemoryStage1Record) -> String) throws {
        try ensureLayout()
        let retained = Array(records.prefix(maxRawMemoriesForConsolidation))
        let keep = Set(retained.map { memory in
            Self.rolloutSummaryFileStem(threadId: memory.threadId,
                                        sourceUpdatedAt: memory.sourceUpdatedAt,
                                        rolloutSlug: memory.rolloutSlug)
        })
        try pruneRolloutSummaries(keeping: keep)
        for memory in retained {
            try writeRolloutSummary(memory, cwd: cwdFor(memory))
        }
    }

    /// prune_rollout_summaries 1:1：目录内 .md 文件 stem 不在 keep 集 → 删除。
    private func pruneRolloutSummaries(keeping keep: Set<String>) throws {
        let dir = rootURL.appendingPathComponent(MemoryConstants.rolloutSummariesSubdir)
        guard let entries = try? Self.fm.contentsOfDirectory(atPath: dir.path) else {
            return // NotFound → Ok(())
        }
        for entry in entries.sorted() {
            guard entry.hasSuffix(".md") else { continue }
            let stem = String(entry.dropLast(2))
            guard !keep.contains(stem) else { continue }
            try? Self.fm.removeItem(at: dir.appendingPathComponent(entry))
        }
    }

    /// write_rollout_summary_for_thread 1:1（git_branch 条件行万我恒缺席）。
    private func writeRolloutSummary(_ memory: MemoryStage1Record, cwd: String) throws {
        let stem = Self.rolloutSummaryFileStem(threadId: memory.threadId,
                                               sourceUpdatedAt: memory.sourceUpdatedAt,
                                               rolloutSlug: memory.rolloutSlug)
        let url = rootURL
            .appendingPathComponent(MemoryConstants.rolloutSummariesSubdir)
            .appendingPathComponent("\(stem).md")
        var body = ""
        body += "thread_id: \(memory.threadId)\n"
        body += "updated_at: \(Self.rfc3339(memory.sourceUpdatedAt))\n"
        body += "rollout_path: \(Self.rolloutPathLabel(memory.threadId))\n"
        body += "cwd: \(cwd)\n"
        body += "\n"
        body += memory.rolloutSummary
        body += "\n"
        try write(body, to: url)
    }

    // MARK: - 文件名 stem（rollout_summary_file_stem_from_parts :161-238 逐字）

    /// 万我会话 id = UUID（SessionStore.createSession）；非 UUID 形态（防御）
    /// 走 codex 非 UUID 臂（31 进制 hash + source_updated_at 时间戳段）。
    static func rolloutSummaryFileStem(threadId: String, sourceUpdatedAt: Int,
                                       rolloutSlug: String?) -> String {
        let rolloutSlugMaxLen = 60
        let alphabet = Array("0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ")
        let shortHashSpace: UInt32 = 14_776_336

        var timestampFragment: String
        var shortHashSeed: UInt32
        if let uuid = UUID(uuidString: threadId) {
            // 万我 UUID 恒 v4（随机）——get_timestamp 无 unix 时间戳面，时间戳段
            // 落 codex 的 unwrap_or(source_updated_at) 臂；hash 种子 = uuid 低
            // 32 位（:183 as_u128 & 0xFFFF_FFFF）。
            timestampFragment = Self.utcFormat(sourceUpdatedAt)
            let raw = uuid.uuid
            let low32 = (UInt32(raw.12) << 24) | (UInt32(raw.13) << 16)
                | (UInt32(raw.14) << 8) | UInt32(raw.15)
            shortHashSeed = low32
        } else {
            var seed: UInt32 = 0
            for byte in threadId.utf8 {
                seed = seed &* 31 &+ UInt32(byte)
            }
            shortHashSeed = seed
            timestampFragment = Self.utcFormat(sourceUpdatedAt)
        }

        var value = shortHashSeed % shortHashSpace
        var chars = Array(repeating: Character("0"), count: 4)
        for idx in stride(from: chars.count - 1, through: 0, by: -1) {
            chars[idx] = alphabet[Int(value % UInt32(alphabet.count))]
            value /= UInt32(alphabet.count)
        }
        let filePrefix = "\(timestampFragment)-\(String(chars))"

        guard let rawSlug = rolloutSlug else { return filePrefix }
        var slug = ""
        for ch in rawSlug {
            if slug.count >= rolloutSlugMaxLen { break }
            if ch.isASCII, ch.isLetter || ch.isNumber {
                slug.append(Character(ch.lowercased()))
            } else {
                slug.append("_")
            }
        }
        while slug.hasSuffix("_") { slug.removeLast() }
        return slug.isEmpty ? filePrefix : "\(filePrefix)-\(slug)"
    }

    // MARK: - Phase2 校验（validate_consolidation_artifacts :51-82）

    /// validate_consolidation_artifacts 1:1：清 symlink → MEMORY.md 存在且为
    /// 文件 → memory_summary.md 首行 == "v1"。
    func validateConsolidationArtifacts() throws {
        let removed = try removeMemorySymlinks()
        guard removed == 0 else {
            throw MemoryError(message:
                "removed \(removed) symbolic links from consolidated memory workspace")
        }
        let memoryPath = rootURL.appendingPathComponent("MEMORY.md")
        var isDir: ObjCBool = false
        guard Self.fm.fileExists(atPath: memoryPath.path, isDirectory: &isDir),
              !isDir.boolValue else {
            throw MemoryError(message:
                "consolidated memory artifact missing or not a file: \(memoryPath.path)")
        }
        let summaryPath = rootURL.appendingPathComponent("memory_summary.md")
        guard let summary = try? String(contentsOf: summaryPath, encoding: .utf8) else {
            throw MemoryError(message:
                "read memory summary artifact failed: \(summaryPath.path)")
        }
        guard summary.split(separator: "\n", omittingEmptySubsequences: false)
            .first == "v1" else {
            throw MemoryError(message:
                "memory summary artifact does not start with v1: \(summaryPath.path)")
        }
    }

    // MARK: - symlink 清除（remove_memory_symlinks）

    /// 递归清除 memory 根内符号链接（workspace.rs :84-115 逐语义）；返回清除数。
    @discardableResult
    func removeMemorySymlinks() throws -> Int {
        var directories = [rootURL]
        var removed = 0
        while let directory = directories.popLast() {
            guard let entries = try? Self.fm.contentsOfDirectory(
                at: directory, includingPropertiesForKeys: nil, options: []) else {
                continue
            }
            for entry in entries {
                guard let values = try? entry.resourceValues(forKeys: [.isSymbolicLinkKey,
                                                                       .isDirectoryKey]),
                      let isSymlink = values.isSymbolicLink else { continue }
                if isSymlink {
                    try? Self.fm.removeItem(at: entry)
                    removed += 1
                } else if values.isDirectory == true {
                    directories.append(entry)
                }
            }
        }
        return removed
    }

    // MARK: - 快照清单 diff（已定适配③——GitBaselineDiff 等价承载）

    /// 当前文件树 → 清单（hash = FNV-1a 64 变体，变化检测足够；排除清单文件
    /// 自身与 Phase2 diff 工件——git baseline 不含未跟踪 prompt 工件同语义）。
    func snapshotManifest() -> MemorySnapshotManifest {
        var entries: [String: String] = [:]
        collectEntries(at: rootURL, prefix: "", into: &entries)
        return MemorySnapshotManifest(entries: entries)
    }

    private func collectEntries(at dir: URL, prefix: String,
                                into entries: inout [String: String]) {
        guard let items = try? Self.fm.contentsOfDirectory(
            at: dir, includingPropertiesForKeys: [.isDirectoryKey],
            options: [.skipsHiddenFiles]) else { return }
        for item in items.sorted(by: { $0.lastPathComponent < $1.lastPathComponent }) {
            let name = item.lastPathComponent
            if name == MemoryConstants.phase2WorkspaceDiffFilename { continue }
            let rel = prefix.isEmpty ? name : "\(prefix)/\(name)"
            let isDir = (try? item.resourceValues(forKeys: [.isDirectoryKey]))?
                .isDirectory ?? false
            if isDir {
                collectEntries(at: item, prefix: rel, into: &entries)
            } else if let data = try? Data(contentsOf: item) {
                entries[rel] = Self.fnv1a64(data)
            }
        }
    }

    /// 上次基线清单 → 当前树 diff（git status label 词汇：A/M/D；
    /// path lexicographic——git status 同序）。
    func diffAgainstManifest(_ baseline: MemorySnapshotManifest) -> MemorySnapshotDiff {
        let current = snapshotManifest()
        var changes: [MemorySnapshotDiff.Change] = []
        for path in current.entries.keys.sorted() {
            switch baseline.entries[path] {
            case .none: changes.append(.init(label: "A", path: path))
            case .some(let old) where old != current.entries[path]:
                changes.append(.init(label: "M", path: path))
            default: break
            }
        }
        for path in baseline.entries.keys.sorted() where current.entries[path] == nil {
            changes.append(.init(label: "D", path: path))
        }
        var rendered = "# Memory Workspace Diff\n\n"
        rendered += "Generated by Codex before Phase 2 memory consolidation. "
        rendered += "Read this file first and do not edit it.\n\n"
        rendered += "## Status\n"
        if changes.isEmpty {
            rendered += "- none\n"
        } else {
            for change in changes { rendered += "- \(change.label) \(change.path)\n" }
        }
        rendered += "\n## Diff\n\n```diff\n```\n"
        return MemorySnapshotDiff(changes: changes, renderedDiff: rendered)
    }

    /// 基线读（manifest 缺失/损坏 = 空基线——首次全量 added，等价 git init 后
    /// 首次 diff_since_latest_init 的空树语义）。
    func loadManifest() -> MemorySnapshotManifest {
        guard let data = try? Data(contentsOf: manifestURL),
              let manifest = try? MemorySnapshotManifest.decode(from: data) else {
            return MemorySnapshotManifest(entries: [:])
        }
        return manifest
    }

    /// 基线落盘（reset_memory_workspace_baseline 等价——成功收口时拍新基线）。
    func saveManifest(_ manifest: MemorySnapshotManifest) throws {
        try Self.fm.createDirectory(
            at: manifestURL.deletingLastPathComponent(), withIntermediateDirectories: true)
        try manifest.encode().write(to: manifestURL, options: .atomic)
    }

    // MARK: - Phase2 diff 工件（write_workspace_diff / remove_workspace_diff）

    private var workspaceDiffURL: URL {
        rootURL.appendingPathComponent(MemoryConstants.phase2WorkspaceDiffFilename)
    }

    /// write_workspace_diff 1:1（4MiB 截断在渲染端已保证——Status 行集有界）。
    func writeWorkspaceDiff(_ diff: MemorySnapshotDiff) throws {
        try write(diff.renderedDiff, to: workspaceDiffURL)
    }

    /// remove_workspace_diff 1:1（NotFound 吞掉）。
    func removeWorkspaceDiff() {
        try? Self.fm.removeItem(at: workspaceDiffURL)
    }

    // MARK: - 一键清空（clear_memory_roots_contents 承载——设置页消费）

    /// memory 根目录树整删 + 重建空根（账本清由 MemoryDatabase.clearAll 承担）。
    func clearAll() throws {
        if Self.fm.fileExists(atPath: rootURL.path) {
            try Self.fm.removeItem(at: rootURL)
        }
        try? Self.fm.removeItem(at: manifestURL)
        try ensureLayout()
    }

    // MARK: - 私有

    private func write(_ text: String, to url: URL) throws {
        guard let data = text.data(using: .utf8) else {
            throw MemoryError(message: "utf8 encode failed: \(url.path)")
        }
        try data.write(to: url, options: .atomic)
    }

    /// 万我会话事实源路径标签（codex rollout_path 列位——storage.rs :67；
    /// 万我会话 = groups/default/sessions/<id>.jsonl，取相对事实源标签）。
    private static func rolloutPathLabel(_ threadId: String) -> String {
        "sessions/\(threadId).jsonl"
    }

    /// epoch 秒 → UTC "%Y-%m-%dT%H-%M-%S"（extension_resources FILENAME_TS_FORMAT）。
    static func utcFormat(_ epochSeconds: Int) -> String {
        let date = Date(timeIntervalSince1970: TimeInterval(epochSeconds))
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = TimeZone(identifier: "UTC")
        formatter.dateFormat = "yyyy-MM-dd'T'HH-mm-ss"
        return formatter.string(from: date)
    }

    /// source_updated_at（Int 秒）→ RFC3339（storage.rs :63 to_rfc3339 列语义）。
    static func rfc3339(_ epochSeconds: Int) -> String {
        let date = Date(timeIntervalSince1970: TimeInterval(epochSeconds))
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime]
        return formatter.string(from: date)
    }

    /// FNV-1a 64（快照 hash；十六进制文本）。
    static func fnv1a64(_ data: Data) -> String {
        var hash: UInt64 = 0xcbf29ce484222325
        for byte in data {
            hash = (hash ^ UInt64(byte)) &* 0x100000001b3
        }
        return String(format: "%016llx", hash)
    }
}
